// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARAuxjNmvrzTksivpdEHhukGs7aMtFHOk',
    appId: '1:52583662520:web:70ba2408de71413069c54d',
    messagingSenderId: '52583662520',
    projectId: 'mmmm-7e4ba',
    authDomain: 'mmmm-7e4ba.firebaseapp.com',
    storageBucket: 'mmmm-7e4ba.firebasestorage.app',
    measurementId: 'G-XD3K4KZK9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJXJvP6n4BsTbWUzNGwgpQ6M3oK7pK7k',
    appId: '1:52583662520:android:088b7bd944822d8469c54d',
    messagingSenderId: '52583662520',
    projectId: 'mmmm-7e4ba',
    storageBucket: 'mmmm-7e4ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYtaJ2QkNU1WHMVZ7M-Ntg0f1Eui-gL9k',
    appId: '1:52583662520:ios:0389d90d6832fb1369c54d',
    messagingSenderId: '52583662520',
    projectId: 'mmmm-7e4ba',
    storageBucket: 'mmmm-7e4ba.firebasestorage.app',
    androidClientId: '52583662520-1bojo15jp28chj76t3jeai1n3heomjt8.apps.googleusercontent.com',
    iosClientId: '52583662520-4an41inr9mgd8139ms2bomoft4dc5bjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYtaJ2QkNU1WHMVZ7M-Ntg0f1Eui-gL9k',
    appId: '1:52583662520:ios:0389d90d6832fb1369c54d',
    messagingSenderId: '52583662520',
    projectId: 'mmmm-7e4ba',
    storageBucket: 'mmmm-7e4ba.firebasestorage.app',
    androidClientId: '52583662520-1bojo15jp28chj76t3jeai1n3heomjt8.apps.googleusercontent.com',
    iosClientId: '52583662520-4an41inr9mgd8139ms2bomoft4dc5bjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARAuxjNmvrzTksivpdEHhukGs7aMtFHOk',
    appId: '1:52583662520:web:364f5b76585dd18d69c54d',
    messagingSenderId: '52583662520',
    projectId: 'mmmm-7e4ba',
    authDomain: 'mmmm-7e4ba.firebaseapp.com',
    storageBucket: 'mmmm-7e4ba.firebasestorage.app',
    measurementId: 'G-B2R18CFF81',
  );
}
